09-20 16:27:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1443)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:220)
	at dar.Functions.DBFunctions.runQuery(DBFunctions.java:132)
	at dar.remoteDB.ChangeManager.addResultIntoList(ChangeManager.java:76)
	at dar.remoteDB.ChangeManager.getListOfChanges(ChangeManager.java:49)
	at dar.remoteDB.ChangeManager.<init>(ChangeManager.java:35)
	at dar.remoteDB.DBWrapper.startSync(DBWrapper.java:102)
	at dar.remoteDB.DBWrapper.checkConnection(DBWrapper.java:96)
	at dar.remoteDB.DBWrapper.run(DBWrapper.java:61)
	at java.lang.Thread.run(Thread.java:745)
09-21 11:28:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "START" not found; SQL statement:
SELECT ID, Start FROM UpdateLog where type =0 and (Start is not NULL or End is not null) order by ID desc LIMIT 0,1 [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:75)
	at dar.Functions.DBFunctions.runQuery(DBFunctions.java:133)
	at dar.remoteDB.ChangeManager.getLastUpdate(ChangeManager.java:247)
	at dar.remoteDB.ChangeManager.getListOfChanges(ChangeManager.java:47)
	at dar.remoteDB.ChangeManager.<init>(ChangeManager.java:41)
	at dar.remoteDB.DBWrapper.startSync(DBWrapper.java:102)
	at dar.remoteDB.DBWrapper.checkConnection(DBWrapper.java:96)
	at dar.remoteDB.DBWrapper.run(DBWrapper.java:56)
	at java.lang.Thread.run(Thread.java:745)
09-21 11:28:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "START" not found; SQL statement:
SELECT ID, Start FROM UpdateLog where type =1 and (Start is not NULL or End is not null) order by ID desc LIMIT 0,1 [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:75)
	at dar.Functions.DBFunctions.runQuery(DBFunctions.java:133)
	at dar.remoteDB.ChangeManager.getLastUpdate(ChangeManager.java:247)
	at dar.remoteDB.ChangeManager.getListOfChanges(ChangeManager.java:47)
	at dar.remoteDB.ChangeManager.<init>(ChangeManager.java:41)
	at dar.remoteDB.DBWrapper.startSync(DBWrapper.java:102)
	at dar.remoteDB.DBWrapper.checkConnection(DBWrapper.java:96)
	at dar.remoteDB.DBWrapper.run(DBWrapper.java:56)
	at java.lang.Thread.run(Thread.java:745)
09-21 11:28:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "START" not found; SQL statement:
INSERT INTO UpdateLog (`Start`, `Type`) VALUES ('2016-09-21 11:28:58.919', 0) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Table.getColumn(Table.java:637)
	at org.h2.command.Parser.parseColumn(Parser.java:849)
	at org.h2.command.Parser.parseColumnList(Parser.java:833)
	at org.h2.command.Parser.parseInsert(Parser.java:1033)
	at org.h2.command.Parser.parsePrepared(Parser.java:402)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:128)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:784)
	at dar.Functions.DBFunctions.executeQuery(DBFunctions.java:32)
	at dar.Functions.DBFunctions.dbInsert(DBFunctions.java:186)
	at dar.remoteDB.ChangeManager.createNewUpdate(ChangeManager.java:264)
	at dar.remoteDB.ChangeManager.runSync(ChangeManager.java:110)
	at dar.remoteDB.DBWrapper.startSync(DBWrapper.java:103)
	at dar.remoteDB.DBWrapper.checkConnection(DBWrapper.java:96)
	at dar.remoteDB.DBWrapper.run(DBWrapper.java:56)
	at java.lang.Thread.run(Thread.java:745)
09-21 11:28:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "END" not found; SQL statement:
UPDATE UpdateLog SET End = '2016-09-21 11:28:59.057'  WHERE ID = 0  [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Table.getColumn(Table.java:637)
	at org.h2.command.Parser.readTableColumn(Parser.java:700)
	at org.h2.command.Parser.parseUpdate(Parser.java:734)
	at org.h2.command.Parser.parsePrepared(Parser.java:456)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:128)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:784)
	at dar.Functions.DBFunctions.executeQuery(DBFunctions.java:32)
	at dar.Functions.DBFunctions.dbUpdate(DBFunctions.java:256)
	at dar.remoteDB.ChangeManager.updateFinished(ChangeManager.java:271)
	at dar.remoteDB.ChangeManager.runSync(ChangeManager.java:129)
	at dar.remoteDB.DBWrapper.startSync(DBWrapper.java:103)
	at dar.remoteDB.DBWrapper.checkConnection(DBWrapper.java:96)
	at dar.remoteDB.DBWrapper.run(DBWrapper.java:56)
	at java.lang.Thread.run(Thread.java:745)
09-22 10:17:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1443)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:220)
	at dar.Functions.DBFunctions.runQuery(DBFunctions.java:132)
	at dar.remoteDB.ChangeManager.getLastUpdate(ChangeManager.java:245)
	at dar.remoteDB.ChangeManager.getListOfChanges(ChangeManager.java:45)
	at dar.remoteDB.ChangeManager.<init>(ChangeManager.java:39)
	at dar.remoteDB.DBWrapper.startSync(DBWrapper.java:109)
	at dar.remoteDB.DBWrapper.checkConnection(DBWrapper.java:103)
	at dar.remoteDB.DBWrapper.run(DBWrapper.java:68)
	at java.lang.Thread.run(Thread.java:745)
09-22 10:17:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1443)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:220)
	at dar.Functions.DBFunctions.runQuery(DBFunctions.java:132)
	at dar.remoteDB.ChangeManager.getLastUpdate(ChangeManager.java:245)
	at dar.remoteDB.ChangeManager.getListOfChanges(ChangeManager.java:45)
	at dar.remoteDB.ChangeManager.<init>(ChangeManager.java:39)
	at dar.remoteDB.DBWrapper.startSync(DBWrapper.java:109)
	at dar.remoteDB.DBWrapper.checkConnection(DBWrapper.java:103)
	at dar.remoteDB.DBWrapper.run(DBWrapper.java:68)
	at java.lang.Thread.run(Thread.java:745)
